<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>continue_to_checkout_btn</name>
   <tag></tag>
   <elementGuidId>64b172c3-f4cc-42c0-af44-2a119379ee87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button#submit</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
