<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>email_address</name>
   <tag></tag>
   <elementGuidId>a57ab6c4-f548-4dd1-a636-bb806905a2bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input#email</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
