<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>login_checkbox</name>
   <tag></tag>
   <elementGuidId>e1c4cc70-0370-43de-865f-8586d3449071</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.buy-checkbox__label.ng-binding</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
