<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>go_to_basket_popup</name>
   <tag></tag>
   <elementGuidId>98581335-1d0e-44c5-bcfa-69057d7152a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.button__popup.button__confirm</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
