<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_size_btn</name>
   <tag></tag>
   <elementGuidId>5c63a434-33ec-41cd-804a-0fe834299d11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select.a-size-select__select</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
