<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buy_steps_section</name>
   <tag></tag>
   <elementGuidId>04978e16-07f7-4bd0-88da-7841e4fbf10f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.buy-header</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
