<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkout_btn</name>
   <tag></tag>
   <elementGuidId>b1debe8f-6490-43c6-a2ad-6c1d3fd7191f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button#order-bottom</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
