<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>product_name</name>
   <tag></tag>
   <elementGuidId>b4752e3c-4c1a-48d4-a6d0-a1b3b8c82919</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.hide-mobile>div.checkout-basket__description</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
