<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>product_size</name>
   <tag></tag>
   <elementGuidId>5fb2265c-1208-47b2-bc08-2105152dc1ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>//option[@selected='selected']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//option[@selected='selected']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
