<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>basket_badge</name>
   <tag></tag>
   <elementGuidId>b6521019-4aa3-4f81-8115-087fc584cd91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.badge.badge--basket.ng-binding</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
