<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>go_to_basket_btn</name>
   <tag></tag>
   <elementGuidId>e6d95505-f504-4760-b3cf-9dcc26bd8d60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.button__basket.ng-binding</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
