<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>account_Panel</name>
   <tag></tag>
   <elementGuidId>8029a90b-6973-4146-92bb-db79949c4d33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div#I1688092588-flyout</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
